- name: copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  become: yes

- name: remove default conf
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx
  become: yes

- name: copy nginx conf close version
  template:
    src: servertoken.conf.j2
    dest: /etc/nginx/sites-enabled/servertoken.conf
  notify: reload nginx
  become: yes
